### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by Matthww**

### CODE REVIEW

**Comment by Vaults1** [comment]
Pinged everyone so they can have a look.

**Comment by Ad5001** [comment]
I don't see much point bur why not :)

**Comment by Matthww** [comment]
@Ad5001 It looks much cleaner :P

**Review by Ad5001 — APPROVED** [review]
Don't changes much important things but why not :)

**Review by Vaultleaper — APPROVED** [review]
I guess...

**Review by Thunder33345 — COMMENTED** [review]
There's no reject? oh \*shrugs\*
I see no improvements at all
just class name changes

**Comment by Matthww** [comment]
@Thunder33345 I also changed the protocols for PMMP api changes

**Review by HimbeersaftLP — APPROVED** [review]
Nothing major, but okay!

**Review by dragonwocky — APPROVED** [review]
Just makes things a bit simpler, doesn't change any features, but why not?

**Review by Erkam246 — APPROVED** [review]

**Comment by dragonwocky** [comment]
I'm just going to go ahead and merge this if thats ok...

**Review by AvgZing — COMMENTED** [review]
Approved! I don't really see the point, but it is visually more appealing so I like it

**Comment by Taki21** [comment]
lol

**Pull request merged**
